// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA56Y0NhmsYMHwowaphGWSD99e5RvOTv9w',
    appId: '1:869165468961:web:e5307fd1ebf50abda2c260',
    messagingSenderId: '869165468961',
    projectId: 'budgetbuddy-9dbb9',
    authDomain: 'budgetbuddy-9dbb9.firebaseapp.com',
    storageBucket: 'budgetbuddy-9dbb9.firebasestorage.app',
    measurementId: 'G-JZMNP56JKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB29tBT9-Rq51Z4qcXSvqudsEaPmW5MaXY',
    appId: '1:869165468961:android:fa9eaec0ec1fe431a2c260',
    messagingSenderId: '869165468961',
    projectId: 'budgetbuddy-9dbb9',
    storageBucket: 'budgetbuddy-9dbb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAk-_twaQUL7q9DfuyS-6j3O63mK8MV8c',
    appId: '1:869165468961:ios:99f00e2748b05a69a2c260',
    messagingSenderId: '869165468961',
    projectId: 'budgetbuddy-9dbb9',
    storageBucket: 'budgetbuddy-9dbb9.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAk-_twaQUL7q9DfuyS-6j3O63mK8MV8c',
    appId: '1:869165468961:ios:99f00e2748b05a69a2c260',
    messagingSenderId: '869165468961',
    projectId: 'budgetbuddy-9dbb9',
    storageBucket: 'budgetbuddy-9dbb9.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA56Y0NhmsYMHwowaphGWSD99e5RvOTv9w',
    appId: '1:869165468961:web:597ba0abf2e54f84a2c260',
    messagingSenderId: '869165468961',
    projectId: 'budgetbuddy-9dbb9',
    authDomain: 'budgetbuddy-9dbb9.firebaseapp.com',
    storageBucket: 'budgetbuddy-9dbb9.firebasestorage.app',
    measurementId: 'G-7RE9SV84H6',
  );

}